local mod = assert(hsw_nanosuit)

mod:require("upgrades/dense_storage_units.lua")
mod:require("upgrades/energized_suit.lua")
mod:require("upgrades/hardened_suit.lua")
mod:require("upgrades/isotopic_stable_suit.lua")
mod:require("upgrades/mana_circuits.lua")
mod:require("upgrades/micro_electronics_suit.lua")
mod:require("upgrades/nano_element_suit.lua")
mod:require("upgrades/re_initializer.lua")
mod:require("upgrades/reinforced_suit.lua")
mod:require("upgrades/self_repairing_suit.lua")
mod:require("upgrades/self_replicating_element_suit.lua")
mod:require("upgrades/smart_element_suit.lua")
mod:require("upgrades/wexkyr_spinal_implant.lua")
