local mod = assert(hsw_worldgen)

mod:require("nodes/dark_stone.lua")
mod:require("nodes/dark_stone_decor.lua")
mod:require("nodes/light_stone.lua")
mod:require("nodes/light_stone_decor.lua")
mod:require("nodes/dark_light_stone.lua")
mod:require("nodes/moonstone_lamp.lua")
mod:require("nodes/oil_stone.lua")
mod:require("nodes/oil_stone_well.lua")
