local mod = assert(hsw_farming)

mod:require("items/beetroot.lua")
mod:require("items/carrot.lua")
mod:require("items/cocoa_beans.lua")
mod:require("items/cotton.lua")
mod:require("items/dried_kelp.lua")
mod:require("items/flax.lua")
mod:require("items/grapes.lua")
mod:require("items/kelp.lua")
mod:require("items/potato.lua")
mod:require("items/rice.lua")
mod:require("items/sugar.lua")
mod:require("items/tomato.lua")
mod:require("items/turnip.lua")
mod:require("items/wheat.lua")
