hsw_campaign:require("chapters/00-prologue.lua")
hsw_campaign:require("chapters/01-settling_in.lua")
-- hsw_campaign:require("chapters/02-rise_of_the_dead.lua")
-- hsw_campaign:require("chapters/03-bio_laboratory.lua")
-- hsw_campaign:require("chapters/04-fusion_reactor.lua")
-- hsw_campaign:require("chapters/05-magic_unleashed.lua")
-- hsw_campaign:require("chapters/06-nuclear_disposal.lua")
-- hsw_campaign:require("chapters/07-celestial_tower_revisit.lua")
-- hsw_campaign:require("chapters/08-elementals_arise.lua")
-- hsw_campaign:require("chapters/09-element_fabrication.lua")
-- hsw_campaign:require("chapters/10-beginning_of_envy.lua")
-- hsw_campaign:require("chapters/11-a_grudge_outlasting_time.lua")
-- hsw_campaign:require("chapters/12-the_fallen_goddess.lua")
