local mod = hsw_tools

mod:require("tools/axes.lua")
mod:require("tools/crowbars.lua")
mod:require("tools/displacement_wands.lua")
mod:require("tools/guns.lua")
mod:require("tools/hammers.lua")
mod:require("tools/hatchets.lua")
mod:require("tools/hoes.lua")
mod:require("tools/knives.lua")
mod:require("tools/needles.lua")
mod:require("tools/pickaxes.lua")
mod:require("tools/saws.lua")
mod:require("tools/spades.lua")
mod:require("tools/spears.lua")
